{% set version = "0.3.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-admm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ADMM_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ADMM/ADMM_{{ version }}.tar.gz
  sha256: b65d8250813dfdaacf4092eb5e9ed4f21b383ac2ba7c8b6a177e1fe92dc0cb33

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rlapack.dll'  # [win]
    - '*/Rblas.dll'    # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ compiler('fortran') }}        # [osx and arm64]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-matrix                     # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-rcpparmadillo              # [build_platform != target_platform]
    - r-rdpack                     # [build_platform != target_platform]
    - r-doparallel                 # [build_platform != target_platform]
    - r-foreach                    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-rdpack
    - r-doparallel
    - r-foreach
    - libblas
    - liblapack
    - libgomp          # [not osx]
    - llvm-openmp      # [osx]
  run:
    - r-base
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-rdpack
    - r-doparallel
    - r-foreach
    - libgomp          # [win]

test:
  commands:
    - $R -e "library('ADMM')"           # [not win]
    - "\"%R%\" -e \"library('ADMM')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ADMM
  license: GPL-3.0-or-later
  summary: Provides algorithms to solve popular optimization problems in statistics such as regression or denoising based on Alternating Direction Method of Multipliers (ADMM). See Boyd et al (2010) <doi:10.1561/2200000016> for complete introduction to the method.
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
  recipe-maintainers:
    - conda-forge/r
    - TanguyGen

# Package: ADMM
# Type: Package
# Title: Algorithms using Alternating Direction Method of Multipliers
# Version: 0.3.3
# Authors@R: c(person("Kisung", "You", role = c("aut", "cre"), email = "kisungyou@outlook.com",comment=c(ORCID="0000-0002-8584-459X")),person("Xiaozhi","Zhu",role="aut",email="xzhu4@nd.edu"))
# Description: Provides algorithms to solve popular optimization problems in statistics such as regression or denoising based on Alternating Direction Method of Multipliers (ADMM). See Boyd et al (2010) <doi:10.1561/2200000016> for complete introduction to the method.
# License: GPL (>= 3)
# Encoding: UTF-8
# Imports: Rcpp, Matrix, Rdpack, stats, doParallel, foreach, parallel, utils
# LinkingTo: Rcpp, RcppArmadillo
# RoxygenNote: 7.1.1
# RdMacros: Rdpack
# NeedsCompilation: yes
# Packaged: 2021-08-07 04:02:53 UTC; kisung
# Author: Kisung You [aut, cre] (<https://orcid.org/0000-0002-8584-459X>), Xiaozhi Zhu [aut]
# Maintainer: Kisung You <kisungyou@outlook.com>
# Repository: CRAN
# Date/Publication: 2021-08-08 04:20:08 UTC
